### ISSUE TITLE
Code arrangement to follow Global standard

### ISSUE THREAD

**Issue by mohsinali421** [PritSapariya/shopping-list-MEAN-stack#1]
Hi ,
  I have Forked your project and wanted to contribute in it and will restructure the code in same directory without explicitly describing as "client code" and "server code". You have created these two separate folders in code which should not be there. I will combine them both and will also add some other cool features.

You have to help me running the code in my machine.

I have cloned in my local system and now facing problem to run the code.

**Comment by PritSapariya** [comment]
Hello,
First of all thanks to connecting with me.
Currently I am learning AngularJS and ReactJS and this repository is also a part of my learning path of AngularJS. I initially thought to do Forntend with AngularJS later on one of my friend and I decide to go with ReactJS. But if want to contribute to this it will be fine we go with AngularJS but to be honest I have zero experience with AngularJS. I can contribute with server part but I need some time to AngularJS. 

If you want to contribute then reply me I will not restructure the repo. 

You have mentioned that you are facing some problem to run the code. May I know what kind of issue ? I will be happy to help you out.

Thanks

**Comment by mohsinali421** [comment]
No issue, Go ahead with your learning. I will be working on some different project
